import type { Stock, StockId } from "../game/types";
import { deriveInitialFundamentals } from "../game/fundamentals";
import { buildInitialDailyCandles } from "../game/charting";
import { createInitialShrimpCohorts } from "./shrimpCohorts";

type StockTemplate = Omit<
  Stock,
  | "chart"
  | "dailyCandles"
  | "microPrice"
  | "microstructure"
  | "shrimpCohorts"
  | "sharesOutstanding"
  | "fairPe"
  | "earningsPerShare"
  | "netProfit"
  | "profitGrowth"
>;

export const stockTemplates: Record<StockId, StockTemplate> = {
  DRAGON_SOFT: {
    id: "DRAGON_SOFT",
    name: "DragonSoft Systems",
    sector: "tech",
    boardType: "growth",
    price: 18.6,
    previousClose: 18.6,
    open: 18.6,
    high: 18.6,
    low: 18.6,
    marketCap: 6_200_000_000,
    floatShares: 155_000_000,
    baseLiquidity: 48_000_000,
    currentLiquidity: 48_000_000,
    turnover: 0,
    volume: 0,
    pe: 96,
    financialHealth: 48,
    sentiment: 62,
    attention: 66,
    momentum: 18,
    heat: 22,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 68,
      dipBuyers: 42,
      newsFollowers: 66,
      gamblers: 74,
      bagholders: 28,
      panicSellers: 22,
      greed: 64,
      fear: 26,
      attention: 66,
      boardFaith: 42
    },
    quantPresence: 58,
    institutionPresence: 22,
    avgHolderCost: 17.8,
    costDistribution: {
      deepProfit: 10,
      profit: 25,
      nearCost: 35,
      loss: 22,
      deepLoss: 8
    },
    activeModifiers: [],
    halted: false
  },
  NEW_HORIZON_BIO: {
    id: "NEW_HORIZON_BIO",
    name: "New Horizon Bio",
    sector: "biotech",
    boardType: "growth",
    price: 24.2,
    previousClose: 24.2,
    open: 24.2,
    high: 24.2,
    low: 24.2,
    marketCap: 8_900_000_000,
    floatShares: 138_000_000,
    baseLiquidity: 54_000_000,
    currentLiquidity: 54_000_000,
    turnover: 0,
    volume: 0,
    pe: 128,
    financialHealth: 44,
    sentiment: 55,
    attention: 52,
    momentum: 4,
    heat: 18,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 52,
      dipBuyers: 36,
      newsFollowers: 76,
      gamblers: 65,
      bagholders: 35,
      panicSellers: 28,
      greed: 55,
      fear: 34,
      attention: 52,
      boardFaith: 38
    },
    quantPresence: 48,
    institutionPresence: 28,
    avgHolderCost: 25.4,
    costDistribution: {
      deepProfit: 6,
      profit: 18,
      nearCost: 31,
      loss: 32,
      deepLoss: 13
    },
    activeModifiers: [],
    halted: false
  },
  GOLDEN_ROOF: {
    id: "GOLDEN_ROOF",
    name: "Golden Roof Properties",
    sector: "property",
    boardType: "main",
    price: 6.4,
    previousClose: 6.4,
    open: 6.4,
    high: 6.4,
    low: 6.4,
    marketCap: 4_400_000_000,
    floatShares: 420_000_000,
    baseLiquidity: 38_000_000,
    currentLiquidity: 38_000_000,
    turnover: 0,
    volume: 0,
    pe: 8,
    financialHealth: 24,
    sentiment: 32,
    attention: 58,
    momentum: -24,
    heat: 30,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 26,
      dipBuyers: 58,
      newsFollowers: 45,
      gamblers: 46,
      bagholders: 72,
      panicSellers: 55,
      greed: 32,
      fear: 65,
      attention: 58,
      boardFaith: 22
    },
    quantPresence: 34,
    institutionPresence: 18,
    avgHolderCost: 8.1,
    costDistribution: {
      deepProfit: 2,
      profit: 8,
      nearCost: 18,
      loss: 42,
      deepLoss: 30
    },
    activeModifiers: [],
    halted: false
  },
  PEARL_DAILY: {
    id: "PEARL_DAILY",
    name: "Pearl Daily Goods",
    sector: "consumer",
    boardType: "main",
    price: 38.5,
    previousClose: 38.5,
    open: 38.5,
    high: 38.5,
    low: 38.5,
    marketCap: 92_000_000_000,
    floatShares: 980_000_000,
    baseLiquidity: 210_000_000,
    currentLiquidity: 210_000_000,
    turnover: 0,
    volume: 0,
    pe: 26,
    financialHealth: 82,
    sentiment: 60,
    attention: 38,
    momentum: 5,
    heat: 6,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 34,
      dipBuyers: 62,
      newsFollowers: 39,
      gamblers: 18,
      bagholders: 22,
      panicSellers: 18,
      greed: 45,
      fear: 24,
      attention: 38,
      boardFaith: 35
    },
    quantPresence: 38,
    institutionPresence: 74,
    avgHolderCost: 37.2,
    costDistribution: {
      deepProfit: 8,
      profit: 28,
      nearCost: 46,
      loss: 15,
      deepLoss: 3
    },
    activeModifiers: [],
    halted: false
  },
  RED_RIVER_LITHIUM: {
    id: "RED_RIVER_LITHIUM",
    name: "Red River Lithium",
    sector: "resources",
    boardType: "main",
    price: 12.8,
    previousClose: 12.8,
    open: 12.8,
    high: 12.8,
    low: 12.8,
    marketCap: 18_000_000_000,
    floatShares: 510_000_000,
    baseLiquidity: 82_000_000,
    currentLiquidity: 82_000_000,
    turnover: 0,
    volume: 0,
    pe: 34,
    financialHealth: 57,
    sentiment: 55,
    attention: 49,
    momentum: 8,
    heat: 12,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 50,
      dipBuyers: 46,
      newsFollowers: 47,
      gamblers: 52,
      bagholders: 34,
      panicSellers: 30,
      greed: 52,
      fear: 32,
      attention: 49,
      boardFaith: 36
    },
    quantPresence: 46,
    institutionPresence: 42,
    avgHolderCost: 12.1,
    costDistribution: {
      deepProfit: 8,
      profit: 31,
      nearCost: 37,
      loss: 18,
      deepLoss: 6
    },
    activeModifiers: [],
    halted: false
  },
  HARBOR_BANK: {
    id: "HARBOR_BANK",
    name: "Harbor Commercial Bank",
    sector: "finance",
    boardType: "main",
    price: 5.15,
    previousClose: 5.15,
    open: 5.15,
    high: 5.15,
    low: 5.15,
    marketCap: 210_000_000_000,
    floatShares: 18_000_000_000,
    baseLiquidity: 330_000_000,
    currentLiquidity: 330_000_000,
    turnover: 0,
    volume: 0,
    pe: 5,
    financialHealth: 76,
    sentiment: 48,
    attention: 28,
    momentum: -2,
    heat: 3,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 18,
      dipBuyers: 54,
      newsFollowers: 28,
      gamblers: 10,
      bagholders: 30,
      panicSellers: 18,
      greed: 30,
      fear: 28,
      attention: 28,
      boardFaith: 24
    },
    quantPresence: 22,
    institutionPresence: 84,
    avgHolderCost: 5.22,
    costDistribution: {
      deepProfit: 2,
      profit: 16,
      nearCost: 60,
      loss: 18,
      deepLoss: 4
    },
    activeModifiers: [],
    halted: false
  },
  SKY_SHIELD: {
    id: "SKY_SHIELD",
    name: "Sky Shield Systems",
    sector: "defense",
    boardType: "main",
    price: 16.75,
    previousClose: 16.75,
    open: 16.75,
    high: 16.75,
    low: 16.75,
    marketCap: 14_500_000_000,
    floatShares: 260_000_000,
    baseLiquidity: 66_000_000,
    currentLiquidity: 66_000_000,
    turnover: 0,
    volume: 0,
    pe: 58,
    financialHealth: 61,
    sentiment: 60,
    attention: 63,
    momentum: 14,
    heat: 16,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 58,
      dipBuyers: 40,
      newsFollowers: 58,
      gamblers: 62,
      bagholders: 26,
      panicSellers: 24,
      greed: 58,
      fear: 30,
      attention: 63,
      boardFaith: 40
    },
    quantPresence: 50,
    institutionPresence: 36,
    avgHolderCost: 15.9,
    costDistribution: {
      deepProfit: 6,
      profit: 33,
      nearCost: 39,
      loss: 17,
      deepLoss: 5
    },
    activeModifiers: [],
    halted: false
  },
  EAST_GRID_ENERGY: {
    id: "EAST_GRID_ENERGY",
    name: "East Grid Energy",
    sector: "energy",
    boardType: "main",
    price: 9.7,
    previousClose: 9.7,
    open: 9.7,
    high: 9.7,
    low: 9.7,
    marketCap: 68_000_000_000,
    floatShares: 4_200_000_000,
    baseLiquidity: 175_000_000,
    currentLiquidity: 175_000_000,
    turnover: 0,
    volume: 0,
    pe: 17,
    financialHealth: 79,
    sentiment: 54,
    attention: 34,
    momentum: 1,
    heat: 4,
    buyQueue: 0,
    sellQueue: 0,
    boardStrength: 0,
    boardState: "loose",
    retail: {
      momentum: 25,
      dipBuyers: 57,
      newsFollowers: 34,
      gamblers: 18,
      bagholders: 24,
      panicSellers: 20,
      greed: 36,
      fear: 26,
      attention: 34,
      boardFaith: 27
    },
    quantPresence: 28,
    institutionPresence: 72,
    avgHolderCost: 9.45,
    costDistribution: {
      deepProfit: 5,
      profit: 24,
      nearCost: 50,
      loss: 17,
      deepLoss: 4
    },
    activeModifiers: [],
    halted: false
  }
};

export function createStocks(): Record<StockId, Stock> {
  return Object.fromEntries(
    Object.entries(stockTemplates).map(([id, stock]) => {
      const fundamentals = deriveInitialFundamentals(stock);

      const initializedStock: Stock = {
        ...stock,
        ...fundamentals,
        microPrice: stock.price,
        microstructure: {
          flowMemory: 0,
          liquidityStress: 0,
          shockMemory: 0,
          lastPrintSign: 0
        },
        shrimpCohorts: createInitialShrimpCohorts(stock),
        retail: { ...stock.retail },
        costDistribution: { ...stock.costDistribution },
        activeModifiers: [...stock.activeModifiers],
        chart: [
          {
            day: 1,
            tick: 0,
            price: stock.price,
            boardState: stock.boardState
          }
        ],
        dailyCandles: []
      };
      initializedStock.dailyCandles = buildInitialDailyCandles(initializedStock);

      return [id, initializedStock];
    })
  ) as Record<StockId, Stock>;
}
